spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://39.108.225.159/demo_test1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12358jfl.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    password: 123456
    timeout: 100000
    jedis:
      pool:
        # 最小空闲连接
        min-idle: 5
        # 最大空闲连接
        max-idle: 20
        # 最大连接数
        max-active: 20
        # 最大阻塞等待时间
        max-wait: 2

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

mybatis:
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    default-executor-type: simple
  type-aliases-package: com.linjunfeng.demo.mybatis.model
  mapper-locations: classpath:mapping/*.xml

server:
  port: 9092